apiVersion: v1
kind: Pod
metadata:
  name: piccolo-pingpong
spec:
  containers:
  - name: ping-container
    image: sdv.lge.com/library/passive-redundant-ping:0.1
  - name: pong-container
    image: sdv.lge.com/library/passive-redundant-pong:0.2
