# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Scenario
metadata:
  name: version-display
spec:
  conditions:
    express: Equal
    value: "parking"
    operands:
      type: DDS
      name: gear_state
      value: "rt/piccolo/gear_state"
  actions:
    - operation: download
  targets:
    - name: "/root/piccolo_yaml/version-display"