# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

version: "3"
name: "piccolo-reconcile-test"
services:
  light-dev:
    network_mode: "host"
    image: sdv.lge.com/library/dummy_light_dev:py0.3
    command: python3 -u /app/main.py
  light-show:
    network_mode: "host"
    image: sdv.lge.com/library/dummy_light_show:py0.1
    command: python3 -u /app/main.py
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/.Xauthority:/root/.Xauthority
    environment:
      DISPLAY: ":0"
