# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

version: "3"
name: "piccolo-reconcile-test"
services:
#  dummy-gateway:
#    network_mode: "host"
#    image: sdv.lge.com/library/piccolo-reconcile:0.1
#    image: localhost/piccolo:1.0
#    command: /piccolo/dummy-gateway
#    volumes:
#      - /root/work/projects-rust/piccolo-bluechi/piccolo.ini:/piccolo/piccolo.ini
#  dummy-light-controller:
#    network_mode: "host"
#    privileged: true
#    image: localhost/piccolo:1.0
#    volumes:
#      - /root/work/projects-rust/piccolo-bluechi/piccolo.ini:/piccolo/piccolo.ini
#    command: /piccolo/dummy-light-controller
  light-dev:
    network_mode: "host"
    image: sdv.lge.com/library/dummy_light_dev:py0.3
    command: python3 -u /app/main.py
  light-show:
    network_mode: "host"
    image: sdv.lge.com/library/dummy_light_show:py0.1
    command: python3 -u /app/main.py
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /root/.Xauthority:/root/.Xauthority
    environment:
      DISPLAY: ":0"
