# SPDX-FileCopyrightText: Copyright 2024 LG Electronics Inc.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Scenario
metadata:
  name: version-cli
spec:
  conditions:
    express: Equal
    value: "neutral"
    operands:
      type: DDS
      name: gear_state
      value: "rt/piccolo/gear_state"
  actions:
    - operation: terminate
  targets:
    - name: "version-cli-1"
